In [4]:
import numpy as np

array=np.array([1,2,3,4,5])
print(array)



[1 2 3 4 5]


In [8]:
import numpy as np

array=np.array([1,2])
print(array)
print(type(array))
array.shape


[1 2]
<class 'numpy.ndarray'>


(2,)

In [21]:
import numpy as np
new_array=np.array([[1,2,3],
                   [4,5,6]])
print(new_array)
new_array.shape


[[1 2 3]
 [4 5 6]]


(2, 3)

In [26]:
num_array=np.array([[1,2,3],[4,5,6],
                   [6,7,8]])
print(num_array)
num_array.shape

[[1 2 3]
 [4 5 6]
 [6 7 8]]


(3, 3)

In [23]:
arrays=np.array([[1,2,3],[4,5,6],
                 [7,8,9],[10,11,12]])
print(arrays)
arrays.shape

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


(4, 3)

In [24]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],
              [10,11,12],[13,14,15],[16,17,18]])
print(arr)
arr.shape

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


(6, 3)

In [ ]:
import numpy as np
import sys

s=[0,1,2,3,4,5,6,7,8,9]
print("Size of each element of list in bytes:",sys.getsizeof(s))



Size of each element of list in bytes: 136


In [30]:
# declaring a numpy array of 10 elements

D=np.array([0,1,2,3,4,5,6,7,8,9])
print("size of each element of the numpy array in bytes:",D.itemsize)
print("size of the whole numpy array in bytes:",D.size*D.itemsize)

size of each element of the numpy array in bytes: 8
size of the whole numpy array in bytes: 80


In [2]:
import numpy as np
import time
# size of arrays and lists
size=100000

list1=range(size)
list2=range(size)

# declaring arrays
array1=np.arange(size)
array2=np.arange(size)

initialTime=time.time()
resultantList=[(a*b) for a,b in zip(list1,list2)]

print("Time taken by Lists to perform multiplication:",(time.time()-initialTime),"seconds")
initialTime=time.time()

resultantArray=array1*array2
print("Time taken by Numpy Arrays to perform multiplication:",(time.time()-initialTime),"seconds")


Time taken by Lists to perform multiplication: 0.018550395965576172 seconds
Time taken by Numpy Arrays to perform multiplication: 0.0014019012451171875 seconds


In [35]:
ndarr=np.array([1,2,3,4,5])
print(arr)
print(ndarr.shape)

[1 2 3 4 5]
(5,)


In [ ]:
# .ndim - Which dimension

new_arr=np.array([[1,2],
                 [3,4]])
print(new_arr.ndim)

# .size - Total elements

print(new_arr.size)



2
4


In [49]:
a=np.array([[1,2,10],[3,4,14],
           [5,6,12],[7,8,9]])
print(a)
print(a.dtype)

[[ 1  2 10]
 [ 3  4 14]
 [ 5  6 12]
 [ 7  8  9]]
int64


In [48]:
b=np.array([[1,2,3,4,5]])
arrytype=b.astype('float64')
print(arrytype)


[[1. 2. 3. 4. 5.]]


In [ ]:
# .asarray - Conversion in array
li=[1,2,3,4,5]
new_list=(np.asarray(li))
print(new_list)

[1 2 3 4 5]


In [58]:
tup=(1,2,3,4)
new_tup=(np.asarray(tup))
print(new_tup)

[1 2 3 4]


In [59]:
lis=([1,2],[3,4])
new_lis=(np.asarray(lis))
print(new_lis)

[[1 2]
 [3 4]]


In [62]:
tup=(1,2,12),(3,4,14),(5,6,16),(7,8,9)
new_tu=(np.asarray(tup))
print(new_tu)

[[ 1  2 12]
 [ 3  4 14]
 [ 5  6 16]
 [ 7  8  9]]


In [ ]:
# Slicing

num=np.arange(10)
print(num)
print(num[3:7])




[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6]


In [ ]:
import numpy as np
num=np.random.random(10)
print(num)

[0.38995115 0.1688458  0.09602496 0.87209559 0.42094603 0.65452709
 0.82740943 0.73868993 0.39754326 0.68197376]


In [1]:
a=[[1,2,3],[4,5,6],[7,8,9]]
   
print(a[2:5])
print(a[::2])
print(a[0:2:-1])




[[7, 8, 9]]
[[1, 2, 3], [7, 8, 9]]
[]


In [1]:
import numpy as np
arr=np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [2]:
a=np.ones((3,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
x=np.full((3,3),20)
print(x)

[[20 20 20]
 [20 20 20]
 [20 20 20]]


In [ ]:
#Basic Array Creation

# 1D numpy array with numbers 1 to 10
import numpy as np
x=np.arange(1,11)
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [9]:
# Numpy array of zeros of size 5
num=np.zeros(5,dtype=int)
print(num)

[0 0 0 0 0]


In [14]:
# Numpy array of size 4*4
arr=np.ones((4,4),dtype=int)
print(arr)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [16]:
# Even numbers from 2 to 20
even_num=np.arange(2,21,2)
print(even_num)


[ 2  4  6  8 10 12 14 16 18 20]


In [18]:
# Create an array with values 10 to 50 step 5
arr=np.arange(10,51,5)
print(arr)

[10 15 20 25 30 35 40 45 50]


In [21]:
# Array Operations

#Create an array [1,2,3] and multiply it by 3
a=np.array([1,2,3])*3
print(a)


[3 6 9]


In [24]:
# Create 2 arrays and add them element wise
x=np.array([1,2,3,4])
y=np.array([4,0,5,4])
print(x+y)





[5 2 8 8]


In [28]:
# Create an array and find is mean
arr1=np.array([10,20,30,40])
mean=np.mean(arr1)
print(mean)

25.0


In [32]:
# Create an array and find square root
arr2=np.array([4,9,16,25])
sqr=np.sqrt(arr2)
print(sqr)

[2. 3. 4. 5.]


In [41]:
# Create an random array of size 5 and its sum
ran=np.random.rand(5)
s=np.sum(ran)
print(s)

2.3631988637814696


In [47]:
# Indexing and slicing
# Slice first 5 elements from an array 1 to 10
ele=np.arange(1,11)
print(ele[:5])

[1 2 3 4 5]


In [48]:
# Get last 2 elements of [10,20,30,40,50]
element=np.array([10,20,30,40,50])
print(element[3:])

[40 50]


In [51]:
# Change 3rd element to 99
elem=np.array([1,2,3,4,5])
elem[2]=99
print(elem)

[ 1  2 99  4  5]


In [2]:
# Create 1D array and reverse it using slicing
import numpy as np
new_arry=np.array([1,2,3,4,5])
rev=new_arry[::-1]
print(rev)

[5 4 3 2 1]


In [5]:
# Random integer between 1 to 100
random_num=np.random.randint(1,101)
print(random_num)

98


In [8]:
# 10 Random num between 0 and 1
r_num=np.random.rand(10)
print(r_num)


[0.05356378 0.90302467 0.49681936 0.94634723 0.71565307 0.06952278
 0.73239868 0.75081484 0.03430618 0.39115584]


In [12]:
# Generate a random array of size 3*3
ran=np.random.rand(3,3)
print(ran)

[[0.68792171 0.37135297 0.2990197 ]
 [0.08990814 0.68004179 0.73155414]
 [0.16561695 0.42995009 0.09262458]]


In [29]:

new_trans=np.array(np.random.randint(5,10,(3,4)))

print(new_trans)
trans=np.transpose(new_trans)
print(trans)

[[6 5 8 7]
 [6 6 5 9]
 [7 6 5 8]]
[[6 6 7]
 [5 6 6]
 [8 5 5]
 [7 9 8]]


In [40]:
reshape=np.array(np.random.randint(10,45,(3,8)))
print(reshape)
print(reshape.shape)
arr=(2,4,3)
s=np.reshape(reshape,arr)
print(s)

[[13 34 40 28 29 35 32 36]
 [23 32 24 25 19 33 33 33]
 [15 32 12 16 39 28 19 24]]
(3, 8)
[[[13 34 40]
  [28 29 35]
  [32 36 23]
  [32 24 25]]

 [[19 33 33]
  [33 15 32]
  [12 16 39]
  [28 19 24]]]


In [26]:
# 5 random numbers normal distribution
r=np.random.randn(5)
print(r)




[ 0.70294501  0.28932712  0.03601308  0.97631202 -1.09753779]


In [24]:
# Shuffle an array [1,2,3,4,5] randomly
r_array=[1,2,3,4,5]
new_rand=np.random.shuffle(r_array)
print(new_rand)

None


In [41]:
resize=np.array(np.random.randint(5,10,(3,4)))
print(resize)
s=(2,4,2)
arr_s=np.resize(resize,s)
print(arr_s)

[[8 8 7 9]
 [7 5 7 7]
 [8 6 7 5]]
[[[8 8]
  [7 9]
  [7 5]
  [7 7]]

 [[8 6]
  [7 5]
  [8 8]
  [7 9]]]


In [43]:
f=np.array(np.random.randint(3,10,(4,3)))
print(f)
arr_f=f.flatten()
print(arr_f)

[[5 8 4]
 [8 5 7]
 [5 9 3]
 [7 4 8]]
[5 8 4 8 5 7 5 9 3 7 4 8]
